### ISSUE TITLE
use gfapy instead of my functions

### ISSUE THREAD

**Issue by jlanga** [jlanga/exfi#16]

**Comment by jlanga** [comment]
Gfa fails when a transcript is just an exon. The path field ask for at least two segments

```
======================================================================
ERROR: Write a single exon GFA
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/work/miniconda3/lib/python3.6/site-packages/gfapy/field/parser.py", line 56, in _parse_gfa_field
    return mod.decode(string)
  File "/home/work/miniconda3/lib/python3.6/site-packages/gfapy/field/oriented_identifier_list_gfa1.py", line 9, in decode
    validate_encoded(string)
  File "/home/work/miniconda3/lib/python3.6/site-packages/gfapy/field/oriented_identifier_list_gfa1.py", line 20, in validate_encoded
    "NameOrient,NameOrient[,NameOrient...])")
gfapy.error.FormatError: 'EXON00000000001+' is not a valid list of GFA1 segment names and orientations
(the segment names must match [!-)+-<>-~][!-~]*;
 the orientations must be + or -;
 the list must be comma-separated NameOrient,NameOrient[,NameOrient...])

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/media/commons/workspace/exfi/exfi/tests/test_io.py", line 43, in test_simple
    filename=tmp_file #tmp_file
  File "/media/commons/workspace/exfi/exfi/io.py", line 132, in write_gfa1
    path=",".join([exon+"+" for exon in paths[transcript_id]])
  File "/home/work/miniconda3/lib/python3.6/site-packages/gfapy/lines/creators.py", line 25, in add_line
    self.__add_line_GFA1(gfa_line)
  File "/home/work/miniconda3/lib/python3.6/site-packages/gfapy/lines/creators.py", line 132, in __add_line_GFA1
    version="gfa1")
  File "/home/work/miniconda3/lib/python3.6/site-packages/gfapy/line/common/construction.py", line 76, in __init__
    self._initialize_positional_fields(data)
  File "/home/work/miniconda3/lib/python3.6/site-packages/gfapy/line/common/construction.py", line 158, in _initialize_positional_fields
    errmsginfo = strings)
  File "/home/work/miniconda3/lib/python3.6/site-packages/gfapy/line/common/construction.py", line 137, in _init_field_value
    line = errmsginfo)
  File "/home/work/miniconda3/lib/python3.6/site-packages/gfapy/field/parser.py", line 72, in _parse_gfa_field
    (err.message if hasattr(err, "message") else str(err))) from err
gfapy.error.FormatError: Line content: ['P', 'ENSDART00000161035.1', 'EXON00000000001+', '*']
Field: segment_names
Datatype: oriented_identifier_list_gfa1
Content: EXON00000000001+
'EXON00000000001+' is not a valid list of GFA1 segment names and orientations
(the segment names must match [!-)+-<>-~][!-~]*;
 the orientations must be + or -;
 the list must be comma-separated NameOrient,NameOrient[,NameOrient...])
```
